name: EC2 auto deploy

on:
 push:
   branches:
     - main
     
jobs:
  build:
   steps:
    - name: Deploy
     run: |
      echo "${{ secrets.PRIVATE_KEY }}" > private_key
      chmod 600 private_keyuncask/kanpai.git"
