name: Next.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.16.0

    - name: Install dependencies
      run: yarn install
      
    - name: Install Next.js
      run: yarn add next
      
    - name: Build
      run: yarn build

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: .next/
